---
title: "CEKit 4.2.0 released"
author: "Nick Cross"
date: 2022-07-11
tags: ["release"]
draft: false
---

This minor CEKit release contains several improvements and bug fixes. You can see
link:https://github.com/cekit/cekit/releases/tag/4.2.0[full release notes here].
Below you can find highlights of this release.


== Support for new follow_tag syntax

Used to denote an image to track the latest version to replace the floating tag in the actual
image with a static tag. This provides more reproducible images.

== Improvements to Behave testing

Fixes for Docker tag interpretaton, schema versioning and test files being ignored.

== Improvements for Dockerfile ordering generation

This resolves issues with included modules using installed packages.

== Availability

This release is immediately available on link:https://pypi.org/project/cekit/[PyPI].

Latest packages submitted for particular Fedora or EPEL versions can be found always in
link:https://bodhi.fedoraproject.org/updates/?packages=cekit[Bodhi]. Besides this you can always
see link:https://koji.fedoraproject.org/koji/packageinfo?packageID=28120[latest CEKit builds in Koji].
