---
title: "CEKit 3.0.1 released"
author: "Marek Goldmann"
date: 2019-04-30
tags: ["release"]
draft: false
---

After link:/blog/2019/04/cekit-3.0.0-released/[initial 3.0.0 release we've done earlier this month] we've gathered feedback and we found that some issues warrant a new bugfix release.

== Changes

Learn more below about these fixes.

=== Fixes in packages and modules installation in overrides

In case packages or modules were defined only in overrides (the main image descriptor did not
have any mention of packages or modules), these were ignored. This was fixed and now you can 
have a pretty much empty image descriptor and define your content in modules only.

https://github.com/cekit/cekit/issues/489

=== Fixes to ODCS service invocation

We found that using the community Fedora ODCS service was a dead code that could not be reached.
This was fixed.

Additionally we made it possible to use ODCS for all local builders: Docker, Podman and Buildah.

https://github.com/cekit/cekit/issues/491

=== Git 1.8 support is back

It looks like CEKit 3.0 introduced an unexpected requirement on Git 2 or later. This was not the intent, so we made it working again with 1.8.

https://github.com/cekit/cekit/pull/494

== Availability

This release is immediately available on link:https://pypi.org/project/cekit/[PyPI]. Packages
were built for Fedora and EPEL too.

Latest packages submitted for particular Fedora or EPEL versions can be found always in
link:https://bodhi.fedoraproject.org/updates/?packages=cekit[Bodhi]. Besides this you can always
see link:https://koji.fedoraproject.org/koji/packageinfo?packageID=28120[latest CEKit builds in Koji].