baseurl = "https://cekit.io/"
languageCode = "en-us"
title = "CEKit"
theme = "hugo-strata-theme"
disqusShortname = "cekit-io"
googleAnalytics = "UA-134837956-1"
paginate = 10

[params]
	name = "CEKit"
	description = "Container image creation tool"
	date_format = "2006-01-02"
	show_read_time = true
	custom_js   = []
	custom_css  = ["css/custom.css"]

	[params.sidebar]
		avatar = "256px.png"
		bio = "Container image development and maintenance simplified"
		twitter = "cekit_project"
		github = "cekit"
		copyright = [
			"&copy; CEKit team",
			"Photo by Samuel Zeller / Unsplash"
		]

	[params.about]
		hide  = false
		title = "Container image creation tool"
		content = "CEKit helps to build container images from image definition files with strong focus on modularity and code reuse."

	[params.features]
		hide  = false
		title = "Features"

	[params.gettingstarted]
		hide  = true
		title = "Getting started"

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "/blog/"
	weight = 20

[[menu.main]]
	name = "Docs"
	url  = "https://cekit.readthedocs.io"
	weight = 30

[[menu.main]]
	name = "GitHub"
	url  = "https://github.com/cekit/cekit"
	weight = 40