version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: sudo apt-get install asciidoctor lftp
      - run: cd ~/bin && curl -L https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.tar.gz | tar xvz
      - run: echo 'export PATH=~/bin:$PATH' >> $BASH_ENV
      - run: hugo -v -d www
      - deploy:
          name: Deploy with SFTP
          command: |
            lftp -e "mirror -R www /www ; bye" -u $SFTP_USER,$SFTP_PASS $SFTP_HOST