version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Prepare host for installation"
          command: |
            sudo killall apt-get || true
            for service in apt-daily.service apt-daily-upgrade.service unattended-upgrades.service apt-daily.timer apt-daily-upgrade.timer; do
              sudo systemctl stop ${service}
              sudo systemctl kill --kill-who=all ${service} || true
              sudo systemctl disable ${service}
              sudo systemctl mask ${service}
            done
            sudo systemctl daemon-reload
      - run:
          name: "Install required packages"
          command: |
            sudo apt-get update
            sudo apt-get install asciidoctor
      - checkout
      - run: git submodule init && git submodule update
      - run: cd ~/bin && curl -L https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.tar.gz | tar xvz
      - run: hugo -v -d www
      - store_artifacts:
          path: www
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - www
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Prepare host for installation"
          command: |
            sudo killall apt-get || true
            for service in apt-daily.service apt-daily-upgrade.service unattended-upgrades.service apt-daily.timer apt-daily-upgrade.timer; do
              sudo systemctl stop ${service}
              sudo systemctl kill --kill-who=all ${service} || true
              sudo systemctl disable ${service}
              sudo systemctl mask ${service}
            done
            sudo systemctl daemon-reload
      - run:
          name: "Install required packages"
          command: |
            sudo apt-get update
            sudo apt-get install lftp
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy with SFTP
          command: |
            lftp -e "mirror -R /tmp/workspace/www /www ; bye" -u $SFTP_USER,$SFTP_PASS $SFTP_HOST

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
