version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: sudo apt-get install asciidoctor hugo
      - run: hugo -v
  deploy:
    machine:
        image: circleci/classic:201808-01
    steps:
      - run:
          name: Deploy with SFTP
          command: |
            sftp -b public/ $SFTP_USER:$SFTP_PASS@$SFTP_HOST:/home/cekitiodef/www
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master