version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: sudo apt-get install asciidoctor hugo lftp
      - run: hugo -v -d www
      - deploy:
          name: Deploy with SFTP
          command: |
            lftp -e "mirror -R www /www ; bye" -u $SFTP_USER,$SFTP_PASS $SFTP_HOST