version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: sudo apt-get install asciidoctor hugo
      - run: hugo -v -d www
      - deploy:
          name: Deploy with SFTP
          command: |
            SSHPASS=$SFTP_PASS sshpass -e sftp -oBatchMode=no -b - sftp $SFTP_USER@$SFTP_HOST:/home/$SFTP_USER << EOF
            cd /home/$SFTP_USER
            put -r www
            bye
            EOF