version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: sudo apt-get install asciidoctor
      - run: cd ~/bin && curl -L https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.tar.gz | tar xvz
      - attach_workspace:
          at: /tmp/workspace
      - run: hugo -v -d /tmp/workspace/www
      - store_artifacts:
          path: /tmp/workspace/www
  deploy:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run: sudo apt-get install lftp
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy with SFTP
          command: |
            lftp -e "mirror -R /tmp/workspace/www /www ; bye" -u $SFTP_USER,$SFTP_PASS $SFTP_HOST

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
